name: nix
on:
  push:
    branches:
      - main
  workflow_dispatch: # allows manual triggering
jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/nix-installer-action@v17
      - name: write README.md
        run: |
          nix develop .#githubActions --command echo "$(nix flake metadata --quiet --json) $(nix flake show --all-systems --quiet --json)" | jq -s add > .github/workflows/data.json
          nix develop .#githubActions --command j2 --customize .github/workflows/customize.py -o README.md .github/workflows/README.md.j2 .github/workflows/data.json
      - name: commit changes
        run: |
          git config user.name "Nix Bot"
          git config user.email "<>"
          git checkout -b nix-update-readme-$GITHUB_RUN_NUMBER
          git add README.md
          git commit -m "[nix] Update README.md"
          git push -u origin nix-update-readme-$GITHUB_RUN_NUMBER
      - name: create pull request
        run: gh pr create -f -l actions -l bot
        env:
          GH_TOKEN: ${{ github.token }}
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/nix-installer-action@v17
      - uses: DeterminateSystems/flake-checker-action@v9
      - run: nix flake check --all-systems
