name: nix
on:
  push:
    branches:
      - main
  workflow_dispatch: # allows manual triggering
jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/nix-installer-action@v16
      - run: nix flake show --all-systems
      - uses: cuchi/jinja2-action@v1.3.0
        with:
          template: .github/workflows/README.md.j2
          output_file: README.md
          variables: |
            nix_flake_metadata=$(nix flake metadata)
            nix_flake_show=$(nix flake show --all-systems)
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/nix-installer-action@v16
      - uses: DeterminateSystems/flake-checker-action@v9
      - run: nix flake check --all-systems
